export const address = [
  {
    title: 'New York',
    street: '30 West 21st street',
    complement: '14th floor',
    city: 'New York, NY 10010',
    country: 'USA',
    phone: '+1 (646) 858-3343',
  },
  {
    title: 'Helsinki',
    street: 'Yliopistonkatu 4 00100 ',
    complement: '',
    city: 'Helsinki',
    country: 'Finland',
    phone: '+358 (0)9 4152 0200',
  },
  {
    title: 'Amsterdam',
    street: 'Looiersgracht 32 1016 VS',
    complement: '',
    city: 'Amsterdam',
    country: 'Netherlands',
    phone: '',
  },
  {
    title: 'Tokyo',
    street: 'Sreed EBISU 2, 4F',
    complement: 'Ebisu 3-28-2',
    city: 'Shibuya-ku Tokyo 150-0013',
    country: 'Japan',
    phone: '日本語',
  },
  {
    title: 'Stockholm',
    street: 'Malmskillnadsgatan 32 5, 111 51 ',
    complement: '',
    city: 'Stockholm',
    country: 'Sweden',
    phone: '',
  },
  {
    title: 'Berlin',
    street: 'Kottbusser Damm 103a, 10967',
    complement: '',
    city: 'Berlin',
    country: 'Germany',
    phone: '',
  },
  {
    title: 'Lisbon',
    street: 'Largo do Duque de Cadaval 17 Fracção I 1200-160',
    complement: '',
    city: 'Lisboa',
    country: 'Portugal',
    phone: '',
  },
];
