export const clientLogos = [
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2018/01/adidas-3-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/04/united-nations-logo-9CBFC2E65F-seeklogo.com_-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2022/01/Epic_Games-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2021/06/netflix-logo-150x0-c-default.webp',
  },
  ,
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/02/Nokia-Logo-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/02/tommy-hilfiger-logo-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/02/varian-logo-black-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/02/heineken-logo-png-file-heineken-logo-svg-1280-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2018/04/2000px-Finnair_Logo.svg_-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2017/10/HBO-1-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2021/06/LFCcrests-Full-Colour-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/02/Suunto_Logo.svg-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2017/10/kone_logo-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/04/ESA_logo_2020_Deep-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2018/04/Air20France-KLM-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/03/viacomcbs_logo-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2017/10/supercell_logo-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2017/10/airbusds_logo-150x0-c-default.webp',
  },
  {
    image:
      'https://www.reaktor.com/wp-content/uploads/2020/02/yle-logo-0220-150x0-c-default.webp',
  },
];
